name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: for d in go/*/ ; do (cd "$d" && go build ./...); done

    - name: Test
      run: for d in go/*/ ; do (cd "$d" && go test ./...); done
    
    - name: Benchmark
      run: for d in go/*/ ; do (cd "$d" && go test -v --bench --benchmem ./...); done
      
    - name: Vet
      run: for d in go/*/ ; do (cd "$d" && go vet ./...); done
      
    - name: Revive Action
      uses: morphy2k/revive-action@v2.2.3
      continue-on-error: true 
      
    - name: Revive Action
      run: for d in go/*/ ; do (cd "$d" && revive ./...); done
      continue-on-error: true 

